public inherited sharing class EPCAppConstants {

    //Describe entity
    public static final String METHOD_DESCRIBE_ENTITY               = 'describeEntity';

    //Generic CRUD
    public static final String METHOD_CREATE_OBJECT                 = 'createObject';
    public static final String METHOD_READ_OBJECT                   = 'readObject';
    public static final String METHOD_UPDATE_OBJECT                 = 'updateObject';
    public static final String METHOD_DELETE_OBJECT                 = 'deleteObject';

    //OfferMigrationComponentMapping
    public static final String METHOD_CREATE_OFFER_MIGRATION_COMPONENT_MAPPING                 = 'createOfferMigrationComponentMapping';
    public static final String METHOD_UPDATE_OFFER_MIGRATION_COMPONENT_MAPPING                 = 'updateOfferMigrationComponentMapping';

    //OfferMigrationPlan
    public static final String METHOD_CREATE_OFFER_MIGRATION_PLAN   = 'createOfferMigrationPlan';
    public static final String METHOD_UPDATE_OFFER_MIGRATION_PLAN   = 'updateOfferMigrationPlan';

    //Product CRUD
    public static final String METHOD_CREATE_PRODUCT                = 'createProduct2';
    public static final String METHOD_READ_PRODUCT                  = 'readProduct2';
    public static final String METHOD_UPDATE_PRODUCT                = 'updateProduct2';
    public static final String METHOD_DELETE_PRODUCT                = 'deleteProduct2';
    public static final String METHOD_AMEND_PRODUCT                 = 'amendProduct2';
    public static final String METHOD_CREATE_VERSION_PRODUCT        = 'createVersionProduct2';

    //ProductChildItem__c CRUD
    public static final String METHOD_CREATE_PCI                    = 'createPCI';
    public static final String METHOD_READ_PCI                      = 'readPCI';
    public static final String METHOD_UPDATE_PCI                    = 'updatePCI';
    public static final String METHOD_DELETE_PCI                    = 'deletePCI';
    
    //Picklist__c CRUD
    public static final String METHOD_CREATE_PICKLIST               = 'createPicklist';
    public static final String METHOD_READ_PICKLIST                 = 'readPicklist';
    public static final String METHOD_UPDATE_PICKLIST               = 'updatePicklist';
    public static final String METHOD_DELETE_PICKLIST               = 'deletePicklist';
    public static final String METHOD_CREATE_VERSION_PICKLIST       = 'createVersionPicklist';

    //PicklistValue__c CRUD
    public static final String METHOD_CREATE_PICKLIST_VALUE        = 'createPicklistValue';
    public static final String METHOD_UPDATE_PICKLIST_VALUE        = 'updatePicklistValue';
    public static final String METHOD_DELETE_PICKLIST_VALUE        = 'deletePicklistValue';

    //PriceList CRUD
    public static final String METHOD_CREATE_PRICELIST              = 'addPriceList';
    public static final String METHOD_READ_PRICELIST                = 'readPriceList';
    public static final String METHOD_UPDATE_PRICELIST              = 'updatePriceList';
    public static final String METHOD_DELETE_PRICELIST              = 'deletePriceList';
    public static final String METHOD_GET_PRICELIST_HIERARCHY       = 'getPriceListHierarchy';

    //Time Plan CRUD
    public static final String METHOD_CREATE_TIME_PLAN              = 'addTimePlan';
    public static final String METHOD_READ_TIME_PLAN                = 'readTimePlan';
    public static final String METHOD_UPDATE_TIME_PLAN              = 'updateTimePlan';
    public static final String METHOD_DELETE_TIME_PLAN              = 'deleteTimePlan';

    // Time Plan Service Methods
    public static final String METHOD_GET_TIME_PLANS_BY_PRICES      = 'getTimePlansByPrices';

    //Time Policy CRUD
    public static final String METHOD_CREATE_TIME_POLICY            = 'addTimePolicy';
    public static final String METHOD_READ_TIME_POLICY              = 'readTimePolicy';
    public static final String METHOD_UPDATE_TIME_POLICY            = 'updateTimePolicy';
    public static final String METHOD_DELETE_TIME_POLICY            = 'deleteTimePolicy';

    //Pricing Plan CRUD
    public static final String METHOD_CREATE_PRICING_PLAN           = 'addPricingPlan';
    public static final String METHOD_READ_PRICING_PLAN             = 'readPricingPlan';
    public static final String METHOD_UPDATE_PRICING_PLAN           = 'updatePricingPlan';
    public static final String METHOD_DELETE_PRICING_PLAN           = 'deletePricingPlan';

    //Pricing Plan Step CRUD
    public static final String METHOD_CREATE_PRICING_PLAN_STEP      = 'addPricingPlanStep';
    public static final String METHOD_READ_PRICING_PLAN_STEP        = 'readPricingPlanStep';
    public static final String METHOD_UPDATE_PRICING_PLAN_STEP      = 'updatePricingPlanStep';
    public static final String METHOD_DELETE_PRICING_PLAN_STEP      = 'deletePricingPlanStep';

    //Pricing Variable CRUD
    public static final String METHOD_CREATE_PRICING_VARIABLE       = 'addPricingVariable';
    public static final String METHOD_READ_PRICING_VARIABLE         = 'readPricingVariable';
    public static final String METHOD_UPDATE_PRICING_VARIABLE       = 'updatePricingVariable';
    public static final String METHOD_DELETE_PRICING_VARIABLE       = 'deletePricingVariable';

    //Pricing charge CRUD
    public static final String METHOD_CREATE_PRICING_CHARGE         = 'addPricingCharge';
    public static final String METHOD_READ_PRICING_CHARGE           = 'readPricingCharge';
    public static final String METHOD_UPDATE_PRICING_CHARGE         = 'updatePricingCharge';
    public static final String METHOD_DELETE_PRICING_CHARGE         = 'deletePricingCharge';

    //Pricing cost CRUD
    public static final String METHOD_CREATE_PRICING_COST           = 'addPricingCost';
    public static final String METHOD_READ_PRICING_COST             = 'readPricingCost';
    public static final String METHOD_UPDATE_PRICING_COST           = 'updatePricingCost';
    public static final String METHOD_DELETE_PRICING_COST           = 'deletePricingCost';

    //Pricing element CRUD
    public static final String METHOD_CREATE_PRICING_ELEMENT        = 'addPricingElement';
    public static final String METHOD_READ_PRICING_ELEMENT          = 'readPricingElement';
    public static final String METHOD_UPDATE_PRICING_ELEMENT        = 'updatePricingElement';
    public static final String METHOD_DELETE_PRICING_ELEMENT        = 'deletePricingElement';

    //Context rule CRUD
    public static final String METHOD_CREATE_CONTEXT_RULE           = 'addContextRule';
    public static final String METHOD_READ_CONTEXT_RULE             = 'readContextRule';
    public static final String METHOD_UPDATE_CONTEXT_RULE           = 'updateContextRule';
    public static final String METHOD_DELETE_CONTEXT_RULE           = 'deleteContextRule';

    //VlocityAttachement CRUD
    public static final String METHOD_CREATE_VLOCITY_ATTACHEMENT    = 'addVlocityAttachment';
    public static final String METHOD_READ_VLOCITY_ATTACHEMENT      = 'readVlocityAttachment';
    public static final String METHOD_UPDATE_VLOCITY_ATTACHEMENT    = 'updateVlocityAttachment';
    public static final String METHOD_DELETE_VLOCITY_ATTACHEMENT    = 'deleteVlocityAttachment';

    //Document CRUD
    public static final String METHOD_CREATE_DOCUMENT               = 'addDocument';
    public static final String METHOD_READ_DOCUMENT                 = 'readDocument';
    public static final String METHOD_UPDATE_DOCUMENT               = 'updateDocument';
    public static final String METHOD_DELETE_DOCUMENT               = 'deleteDocument';

    //Pricing context rule CRUD
    public static final String METHOD_CREATE_PRICING_CONTEXT_RULE   = 'addPricingContextRule';
    public static final String METHOD_READ_PRICING_CONTEXT_RULE     = 'readPricingContextRule';
    public static final String METHOD_UPDATE_PRICING_CONTEXT_RULE   = 'updatePricingContextRule';
    public static final String METHOD_DELETE_PRICING_CONTEXT_RULE   = 'deletePricingContextRule';

    //Pricing context rule CRUD
    public static final String METHOD_CREATE_PRICE_LIST_ENTRY       = 'addPriceListEntry';
    public static final String METHOD_READ_PRICE_LIST_ENTRY         = 'readPriceListEntry';
    public static final String METHOD_UPDATE_PRICE_LIST_ENTRY       = 'updatePriceListEntry';
    public static final String METHOD_DELETE_PRICE_LIST_ENTRY       = 'deletePriceListEntry';

    //Promotion CRUD
    public static final String METHOD_CREATE_PROMOTION              = 'addPromotion';
    public static final String METHOD_READ_PROMOTION                = 'readPromotion';
    public static final String METHOD_UPDATE_PROMOTION              = 'updatePromotion';
    public static final String METHOD_DELETE_PROMOTION              = 'deletePromotion';

    //Promotion Context rule CRUD
    public static final String METHOD_CREATE_PROMOTION_CONTEXT_RULE = 'addPromotionContextRule';
    public static final String METHOD_READ_PROMOTION_CONTEXT_RULE   = 'readPromotionContextRule';
    public static final String METHOD_UPDATE_PROMOTION_CONTEXT_RULE = 'updatePromotionContextRule';
    public static final String METHOD_DELETE_PROMOTION_CONTEXT_RULE = 'deletePromotionContextRule';

    //Promotion item CRUD
    public static final String METHOD_CREATE_PROMOTION_ITEM         = 'addPromotionItem';
    public static final String METHOD_READ_PROMOTION_ITEM           = 'readPromotionItem';
    public static final String METHOD_UPDATE_PROMOTION_ITEM         = 'updatePromotionItem';
    public static final String METHOD_DELETE_PROMOTION_ITEM         = 'deletePromotionItem';

    //Discount CRUD
    public static final String METHOD_CREATE_DISCOUNT               = 'addDiscount';
    public static final String METHOD_READ_DISCOUNT                 = 'readDiscount';
    public static final String METHOD_UPDATE_DISCOUNT               = 'updateDiscount';
    public static final String METHOD_DELETE_DISCOUNT               = 'deleteDiscount';

    //Discount item CRUD
    public static final String METHOD_CREATE_DISCOUNT_ITEM          = 'addDiscountItem';
    public static final String METHOD_READ_DISCOUNT_ITEM            = 'readDiscountItem';
    public static final String METHOD_UPDATE_DISCOUNT_ITEM          = 'updateDiscountItem';
    public static final String METHOD_DELETE_DISCOUNT_ITEM          = 'deleteDiscountItem';

    //Discount pricing CRUD
    public static final String METHOD_CREATE_DISCOUNT_PRICING       = 'addDiscountPricing';
    public static final String METHOD_READ_DISCOUNT_PRICING         = 'readDiscountPricing';
    public static final String METHOD_UPDATE_DISCOUNT_PRICING       = 'updateDiscountPricing';
    public static final String METHOD_DELETE_DISCOUNT_PRICING       = 'deleteDiscountPricing';

    //Discount Context rule CRUD
    public static final String METHOD_CREATE_DISCOUNT_CONTEXT_RULE  = 'addDiscountContextRule';
    public static final String METHOD_READ_DISCOUNT_CONTEXT_RULE    = 'readDiscountContextRule';
    public static final String METHOD_UPDATE_DISCOUNT_CONTEXT_RULE  = 'updateDiscountContextRule';
    public static final String METHOD_DELETE_DISCOUNT_CONTEXT_RULE  = 'deleteDiscountContextRule';

    //Generic Entity CRUD
    public static final String METHOD_CREATE_ENTITY                 = 'createEntity';
    public static final String METHOD_READ_ENTITY                   = 'readEntity';
    public static final String METHOD_UPDATE_ENTITY                 = 'updateEntity';
    public static final String METHOD_DELETE_ENTITY                 = 'deleteEntity';

    //Relationship Type CRUD
    public static final String METHOD_CREATE_RELATION_TYPE              = 'addRelationshipType';
    public static final String METHOD_READ_RELATION_TYPE                = 'readRelationshipType';
    public static final String METHOD_UPDATE_RELATION_TYPE              = 'updateRelationshipType';
    public static final String METHOD_DELETE_RELATION_TYPE              = 'deleteRelationshipType';

      //Product Relationship CRUD
    public static final String METHOD_CREATE_RELATION               = 'addProductRelationship';
    public static final String METHOD_READ_RELATION                 = 'readProductRelationship';
    public static final String METHOD_UPDATE_RELATION               = 'updateProductRelationship';
    public static final String METHOD_DELETE_RELATION               = 'deleteProductRelationship';
    public static final String METHOD_CLONE_RELATION                = 'cloneProductRelationship';

    //Versioning CRUD
    public static final String METHOD_CREATE_NEW_VERSION                 = 'createNewVersion';
    public static final String METHOD_CREATE_NEW_VERSION_OBJECT_TYPE     = 'createNewVersionObjectClass__c';

    public static final String METHOD_GET_ALL_VERSIONS                    = 'getAllVersions';
     //Version Compare
    public static final String METHOD_COMPARE_VERSIONS                 = 'compareVersions';

    //Object Type CRUD
    public static final String METHOD_CREATE_OBJECT_TYPE              = 'createObjectType';
    public static final String METHOD_UPDATE_OBJECT_TYPE              = 'updateObjectObjectClass__c';
    public static final String METHOD_DELETE_OBJECT_TYPE              = 'deleteObjectType';
    public static final String METHOD_READ_OBJECT_TYPE                = 'readObjectClass';


    public static final String METHOD_CREATE_FACETS_OBJECT            = 'createFacetsObject';
    public static final String METHOD_CREATE_OBJECT_FIELD_ATTRIBUTE   = 'createObjectFieldAttribute';
    public static final String METHOD_CREATE_OBJECT_ATTRIBUTE_ASSIGNMENT       = 'createObjectAttributeAssignment';

    //Atrribute assignment CRUD
    public static final String METHOD_CREATE_ATTRIBUTE_ASSIGNMENT           = 'saveAttributeAssignment';
    public static final String METHOD_UPDATE_ATTRIBUTE_ASSIGNMENT           = 'saveAttributeAssignment';
    public static final String METHOD_DELETE_ATTRIBUTE_ASSIGNMENT           = 'deleteObjectAttributeAssignment__c';

    //Object Element CRUD
    public static final String METHOD_CREATE_OBJECT_ELEMENT              = 'createObjectObjectElement__c';
    public static final String METHOD_UPDATE_OBJECT_ELEMENT              = 'updateObjectObjectElement__c';
    public static final String METHOD_DELETE_OBJECT_ELEMENT              = 'deleteObjectObjectElement__c';

    //Object Section CRUD
    public static final String METHOD_CREATE_OBJECT_SECTION              = 'createObjectObjectSection__c';
    public static final String METHOD_DELETE_OBJECT_SECTION              = 'deleteObjectObjectSection__c';

    //Overrides CRUD
    public static final String METHOD_CREATE_OVERRIDE                       = 'createOverride';
    public static final String METHOD_CREATE_OVERRIDE_WITH_EXCLUDED_VALUES  = 'createOverrideWithExcludedValues';
    public static final String METHOD_GET_OVERRIDE                          = 'getOverride';
    public static final String METHOD_GET_OVERRIDE_WITH_EXCLUDED_VALUES     = 'getOverrideWithExcludedValues';
    public static final String METHOD_GET_ATTRIBUTE_OVERRIDE_LIST           = 'getAttributeOverrideList';
    public static final String METHOD_SAVE_OVERRIDE                         = 'saveOverride';
    public static final String METHOD_VALIDATE_AND_SAVE_OVERRIDE            = 'validateAndSaveOverride';
    public static final String METHOD_DELETE_OVERRIDE                       = 'deleteOverride';

    //Override Types
    public static final String TYPE_PRODUCT_DEFINITION                      = 'Product Definition';

    public static final String TYPE_PRODUCT_RELATIONSHIP                        = 'Product Relationship';
    public static final String TYPE_ATTRIBUTE                               = 'Attribute';
    public static final String TYPE_PRICING                                 = 'Pricing';

    //Spec Operations
    public static final String METHOD_GET_SPEC_DETAILS                      = 'getSpecDetails';

    //Work Set Operations
    public static final String METHOD_READ_TARGET_WORK_SETS                 = 'readTargetWorkSets';
    public static final String METHOD_READ_WORK_SET_ITEMS                   = 'readWorkSetItems';
    public static final String METHOD_MOVE_WORK_SET_ITEMS                   = 'moveWorkSetItems';
    public static final String METHOD_DELETE_WORK_SET_ITEMS                 = 'deleteWorkSetItems';
    public static final String METHOD_SET_DEFAULT_WORK_SET                  = 'setDefaultWorkSet';

    public static final String METHOD_CHANGE_PROJECT_STATUS                  = 'changeProjectStatus';
    public static final String METHOD_GET_CURRENT_STATUS                  = 'getCurrentStatus';
    public static final String METHOD_GET_VALID_STATUS                  = 'getValidStatus';
    public static final String METHOD_CHECK_NEXT_STATUS_AVAILABLE                  = 'checkStatusAvailability';
    
    public static final String METHOD_GET_PROJECT_ENABLED='getProjectEnabledStatus';
    public static final String ITEM_ACTION_ADD    = 'Add';
    public static final String ITEM_ACTION_CHANGE = 'Change';
    public static final String ITEM_ACTION_DELETE = 'Delete';
    public static final String ITEM_ACTION_NOCHANGE = 'No Change';

    public static final String DRAFT_STATUS       = 'Draft';
    public static final String IN_REVIEW_STATUS   = 'In-Review';
    public static final String IN_TEST_STATUS     = 'In-Test';
    public static final String RELEASED_STATUS    = 'Released';
    public static final String CANCELLED_STATUS   = 'Canceled';

    //Report Generation methods
    public static final String PRODUCT_REPORT_FOLDER_NAME = 'UPCProductReports';
    public static final String GENERATE_PRODUCT_REPORT    = 'generateProductReport';
    public static final String EXTRACT_PRODUCTS_VIP       = 'UPC_ExtractProductInformation';
    public static final String VIP_SELECTION_TYPE         = 'filtered';
    
    public enum PriceType {CHARGE, COST, ADJUSTMENT}

// added for generic flow
    public static Set<String> CREATE_METHODS=new Set<String>{
        METHOD_CREATE_RELATION_TYPE,
        METHOD_CREATE_RELATION,
        METHOD_CREATE_PRICE_LIST_ENTRY,
        METHOD_CREATE_ENTITY
    };

    public static Set<String> READ_METHODS=new Set<String>{
        METHOD_READ_RELATION_TYPE,
        METHOD_READ_RELATION,
        METHOD_READ_PRICE_LIST_ENTRY,
        METHOD_READ_ENTITY
    };

    public static Set<String> UPDATE_METHODS=new Set<String>{
        METHOD_UPDATE_RELATION_TYPE,
        METHOD_UPDATE_RELATION,
        METHOD_UPDATE_PRICE_LIST_ENTRY,
        METHOD_UPDATE_ENTITY
    };

    public static Set<String> DELETE_METHODS=new Set<String>{
        METHOD_DELETE_RELATION_TYPE,
        METHOD_DELETE_RELATION,
        METHOD_DELETE_PRICE_LIST_ENTRY,
        METHOD_DELETE_ENTITY
    };

    public static Set<String> CLONE_METHODS= new Set<String>{
        METHOD_CLONE_RELATION
    };

    public static Set<String> PRICING_CREATE_METHODS = new Set<String> {
        METHOD_CREATE_PRICELIST,
        METHOD_CREATE_TIME_PLAN,
        METHOD_CREATE_TIME_POLICY,
        METHOD_CREATE_PRICING_PLAN,
        METHOD_CREATE_PRICING_PLAN_STEP,
        METHOD_CREATE_PRICING_VARIABLE,
        METHOD_CREATE_PRICING_CHARGE,
        METHOD_CREATE_PRICING_COST,
        METHOD_CREATE_PRICING_ELEMENT,
        METHOD_CREATE_PRICING_CONTEXT_RULE
    };



    public static Set<String> PRICING_READ_METHODS = new Set<String> {
        METHOD_READ_PRICELIST,
        METHOD_READ_TIME_PLAN,
        METHOD_READ_TIME_POLICY,
        METHOD_READ_PRICING_PLAN,
        METHOD_READ_PRICING_PLAN_STEP,
        METHOD_READ_PRICING_VARIABLE,
        METHOD_READ_PRICING_CHARGE,
        METHOD_READ_PRICING_COST,
        METHOD_READ_PRICING_ELEMENT,
        METHOD_READ_PRICING_CONTEXT_RULE
    };

    public static Set<String> PRICING_UPDATE_METHODS = new Set<String> {
        METHOD_UPDATE_PRICELIST,
        METHOD_UPDATE_TIME_PLAN,
        METHOD_UPDATE_TIME_POLICY,
        METHOD_UPDATE_PRICING_PLAN,
        METHOD_UPDATE_PRICING_PLAN_STEP,
        METHOD_UPDATE_PRICING_VARIABLE,
        METHOD_UPDATE_PRICING_CHARGE,
        METHOD_UPDATE_PRICING_COST,
        METHOD_UPDATE_PRICING_ELEMENT,
        METHOD_UPDATE_PRICING_CONTEXT_RULE
    };

    public static Set<String> PRICING_DELETE_METHODS = new Set<String> {
        METHOD_DELETE_PRICELIST,
        METHOD_DELETE_TIME_PLAN,
        METHOD_DELETE_TIME_POLICY,
        METHOD_DELETE_PRICING_PLAN,
        METHOD_DELETE_PRICING_PLAN_STEP,
        METHOD_DELETE_PRICING_VARIABLE,
        METHOD_DELETE_PRICING_CHARGE,
        METHOD_DELETE_PRICING_COST,
        METHOD_DELETE_PRICING_ELEMENT,
        METHOD_DELETE_PRICING_CONTEXT_RULE
    };
    
     public static Map<String, String> PROJECT_ITEM_ACTION_MAP = new Map<String, String> {
        METHOD_DELETE_OBJECT=>ITEM_ACTION_DELETE,
        METHOD_CREATE_OBJECT=>ITEM_ACTION_ADD,
        METHOD_UPDATE_OBJECT=>ITEM_ACTION_CHANGE,
        METHOD_CREATE_PICKLIST=>ITEM_ACTION_ADD,
        METHOD_UPDATE_PICKLIST=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_PICKLIST=>ITEM_ACTION_DELETE,
        METHOD_CREATE_PICKLIST_VALUE=>ITEM_ACTION_ADD,
        METHOD_UPDATE_PICKLIST_VALUE=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_PICKLIST_VALUE=>ITEM_ACTION_DELETE,
        METHOD_CREATE_PRICELIST=>ITEM_ACTION_ADD,
        METHOD_UPDATE_PRICELIST=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_PRICELIST=>ITEM_ACTION_DELETE,
        METHOD_CREATE_PRICE_LIST_ENTRY=>ITEM_ACTION_ADD,
        METHOD_UPDATE_PRICE_LIST_ENTRY=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_PRICE_LIST_ENTRY=>ITEM_ACTION_DELETE,
        METHOD_CREATE_NEW_VERSION=>ITEM_ACTION_ADD,
        METHOD_VALIDATE_AND_SAVE_OVERRIDE=>ITEM_ACTION_CHANGE,
        METHOD_CREATE_OVERRIDE_WITH_EXCLUDED_VALUES=>ITEM_ACTION_ADD,
        METHOD_CREATE_OVERRIDE=>ITEM_ACTION_ADD,
        METHOD_DELETE_OVERRIDE=>ITEM_ACTION_DELETE,
        METHOD_SAVE_OVERRIDE=>ITEM_ACTION_CHANGE,
        METHOD_CREATE_PROMOTION_ITEM=>ITEM_ACTION_ADD,
        METHOD_DELETE_PROMOTION_ITEM=>ITEM_ACTION_DELETE,
        METHOD_UPDATE_PROMOTION_ITEM=>ITEM_ACTION_CHANGE,
        METHOD_CREATE_DISCOUNT_ITEM=>ITEM_ACTION_ADD,
        METHOD_UPDATE_DISCOUNT_ITEM=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_DISCOUNT_ITEM=>ITEM_ACTION_DELETE,
        METHOD_CREATE_PROMOTION=>ITEM_ACTION_ADD,
        METHOD_UPDATE_PROMOTION=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_PROMOTION=>ITEM_ACTION_DELETE,
        METHOD_CREATE_DISCOUNT=>ITEM_ACTION_ADD,
        METHOD_UPDATE_DISCOUNT=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_DISCOUNT=>ITEM_ACTION_DELETE,
        METHOD_UPDATE_ATTRIBUTE_ASSIGNMENT=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_PRODUCT=>ITEM_ACTION_DELETE,
        METHOD_DELETE_PCI=>ITEM_ACTION_DELETE,
        METHOD_CREATE_PCI=>ITEM_ACTION_ADD,
        METHOD_UPDATE_PCI=>ITEM_ACTION_NOCHANGE,
        METHOD_CREATE_CONTEXT_RULE=>ITEM_ACTION_ADD,
        METHOD_UPDATE_CONTEXT_RULE=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_CONTEXT_RULE=>ITEM_ACTION_DELETE,
        METHOD_CREATE_OBJECT_TYPE=>ITEM_ACTION_ADD,
        METHOD_UPDATE_OBJECT_TYPE=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_OBJECT_TYPE=>ITEM_ACTION_DELETE,
        METHOD_CREATE_OBJECT=>ITEM_ACTION_ADD,
        METHOD_UPDATE_OBJECT_TYPE=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_OBJECT_TYPE=>ITEM_ACTION_DELETE,
        METHOD_CREATE_OBJECT_ELEMENT=>ITEM_ACTION_ADD,
        METHOD_DELETE_OBJECT_SECTION=>ITEM_ACTION_DELETE,
        METHOD_CREATE_OBJECT_ELEMENT=>ITEM_ACTION_ADD,
        METHOD_UPDATE_OBJECT_ELEMENT=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_OBJECT_ELEMENT=>ITEM_ACTION_DELETE,
        METHOD_CREATE_FACETS_OBJECT=>ITEM_ACTION_ADD,
        METHOD_CREATE_DOCUMENT=>ITEM_ACTION_ADD,
        METHOD_UPDATE_DOCUMENT=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_DOCUMENT=>ITEM_ACTION_DELETE,
        METHOD_CREATE_VLOCITY_ATTACHEMENT=>ITEM_ACTION_ADD,
        METHOD_UPDATE_VLOCITY_ATTACHEMENT=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_VLOCITY_ATTACHEMENT=>ITEM_ACTION_DELETE,
        METHOD_CREATE_OBJECT_ATTRIBUTE_ASSIGNMENT=>ITEM_ACTION_ADD,
        METHOD_CREATE_OBJECT_FIELD_ATTRIBUTE=> ITEM_ACTION_ADD,
        METHOD_CREATE_PRICING_ELEMENT=>ITEM_ACTION_ADD,
        METHOD_UPDATE_PRICING_ELEMENT=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_PRICING_ELEMENT=>ITEM_ACTION_DELETE,	
        METHOD_AMEND_PRODUCT=>ITEM_ACTION_CHANGE,
        METHOD_CREATE_PRICING_CONTEXT_RULE=>ITEM_ACTION_ADD,
        METHOD_CREATE_ENTITY=>ITEM_ACTION_ADD,
        METHOD_UPDATE_ENTITY=>ITEM_ACTION_CHANGE,
        METHOD_DELETE_ENTITY=>ITEM_ACTION_DELETE,
        METHOD_DELETE_PRICING_CHARGE=>ITEM_ACTION_DELETE
    };

     public static Map<String, Integer> PROJECT_ITEM_STATUS_MAP = new Map<String, Integer> {
        DRAFT_STATUS=>1,
        IN_REVIEW_STATUS=>2,
        IN_TEST_STATUS=>3, 
        RELEASED_STATUS=>4,
        CANCELLED_STATUS=>5 
    };

    public enum STATUS_STATE { DRAFT_STATUS, 
                                    IN_TEST_STATUS, 
                                    IN_REVIEW_STATUS,
                                    RELEASED_STATUS,
                                    CANCELLED_STATUS

                                    }


    public static Map<Integer, String> PROJECT_ITEM_PRECEDENCE_TO_STATUS_MAP = new Map<Integer,String> {
        1=>DRAFT_STATUS,
        2=>IN_REVIEW_STATUS,
        3=>IN_TEST_STATUS,
        4=>RELEASED_STATUS,
        5=>CANCELLED_STATUS 
    };
}